[package]
name = "MarkServe"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
pulldown-cmark = "0.13.0"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.6", features = ["fs", "trace"] }
